/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package e.voting;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author rizki
 */
public class Voters extends javax.swing.JFrame {

    /**
     * Creates new form Voters
     */
    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null;
    Statement St = null;
    
    private void GetVoters() {
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/evotedb", "root", "");
            St = Con.createStatement();
            String Query = "Select * from tb_vote";
            Rs = St.executeQuery(Query);
            while (Rs.next()) {
                String VoteID = Rs.getString("ID");
                VtrVote.addItem(VoteID);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    private void DisplayVoters() {
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/evotedb", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("Select * from tb_voters");
            VtrTable.setModel(DbUtils.resultSetToTableModel(Rs));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    int VId;
    Statement St1 = null;
    ResultSet Rs1 = null;
    
    private void VotersCount() {
        try {
            St1 = Con.createStatement();
            Rs1 = St1.executeQuery("SELECT MAx(No) from tb_voters");
            Rs1.next();
            VId = Rs1.getInt(1)+1;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    private void WidthColumn() {
        TableColumn column;
        VtrTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        column = VtrTable.getColumnModel().getColumn(0);
        column.setPreferredWidth(30);
        column = VtrTable.getColumnModel().getColumn(1);
        column.setPreferredWidth(200);
        column = VtrTable.getColumnModel().getColumn(2);
        column.setPreferredWidth(35);
        column = VtrTable.getColumnModel().getColumn(3);
        column.setPreferredWidth(150);
        column = VtrTable.getColumnModel().getColumn(4);
        column.setPreferredWidth(55);
        column = VtrTable.getColumnModel().getColumn(5);
        column.setPreferredWidth(60);
        column = VtrTable.getColumnModel().getColumn(6);
        column.setPreferredWidth(65);
        column = VtrTable.getColumnModel().getColumn(7);
        column.setPreferredWidth(40);
    }
    
    public Voters() {
        initComponents();
        GetVoters();
        DisplayVoters();
        WidthColumn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        VtrName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        VtrTable = new javax.swing.JTable();
        AddBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        VtrAge = new javax.swing.JTextField();
        VtrGen = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        VtrVote = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        VtrPw = new javax.swing.JTextField();
        VtrSearch = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        VtrClass = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        VtrMajor = new javax.swing.JComboBox<>();
        DeleteBtnAll = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        VtrClassSrc = new javax.swing.JComboBox<>();
        VtrMajorSrc = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("E-Voting SMK 3 Perguruan Cikini");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setIcon(new javax.swing.ImageIcon("E:\\img skripsi\\Logo_OSIS.svg (2).png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel12)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setIcon(new javax.swing.ImageIcon("E:\\img skripsi\\logo (1).png")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel14)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(0, 0, 255));
        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Manage Voters");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Name");

        VtrName.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        VtrName.setForeground(new java.awt.Color(0, 0, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Age");

        VtrTable.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        VtrTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        VtrTable.setRowHeight(25);
        VtrTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VtrTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(VtrTable);

        AddBtn.setBackground(new java.awt.Color(0, 0, 255));
        AddBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        AddBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddBtn.setText("Add");
        AddBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBtnMouseClicked(evt);
            }
        });

        EditBtn.setBackground(new java.awt.Color(0, 0, 255));
        EditBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        EditBtn.setForeground(new java.awt.Color(255, 255, 255));
        EditBtn.setText("Edit");
        EditBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBtnMouseClicked(evt);
            }
        });

        DeleteBtn.setBackground(new java.awt.Color(0, 0, 255));
        DeleteBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBtn.setText("Delete");
        DeleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBtnMouseClicked(evt);
            }
        });

        BackBtn.setFont(new java.awt.Font("Leelawadee UI", 2, 16)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(0, 0, 255));
        BackBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\rizki\\Pictures\\image project skripsi\\left-arrow (3).png")); // NOI18N
        BackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });

        VtrAge.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        VtrAge.setForeground(new java.awt.Color(0, 0, 255));

        VtrGen.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        VtrGen.setForeground(new java.awt.Color(0, 102, 255));
        VtrGen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Gender");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Vote");

        VtrVote.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        VtrVote.setForeground(new java.awt.Color(0, 102, 255));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Password");

        VtrPw.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        VtrPw.setForeground(new java.awt.Color(0, 0, 255));

        VtrSearch.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        VtrSearch.setForeground(new java.awt.Color(0, 0, 255));
        VtrSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                VtrSearchKeyReleased(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Class");

        VtrClass.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        VtrClass.setForeground(new java.awt.Color(0, 102, 255));
        VtrClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "XI", "XII" }));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Major");

        VtrMajor.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        VtrMajor.setForeground(new java.awt.Color(0, 102, 255));
        VtrMajor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TKJ", "MM", "Farmasi", "OTKP", "TKRO" }));

        DeleteBtnAll.setBackground(new java.awt.Color(0, 0, 255));
        DeleteBtnAll.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        DeleteBtnAll.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBtnAll.setText("Delete All");
        DeleteBtnAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteBtnAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBtnAllMouseClicked(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Search:");

        VtrClassSrc.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        VtrClassSrc.setForeground(new java.awt.Color(0, 102, 255));
        VtrClassSrc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Class--", "X", "XI", "XII" }));
        VtrClassSrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VtrClassSrcActionPerformed(evt);
            }
        });

        VtrMajorSrc.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        VtrMajorSrc.setForeground(new java.awt.Color(0, 102, 255));
        VtrMajorSrc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Major--", "TKJ", "MM", "Farmasi", "OTKP", "TKRO" }));
        VtrMajorSrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VtrMajorSrcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AddBtn)
                        .addGap(18, 18, 18)
                        .addComponent(EditBtn)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteBtn)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteBtnAll))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(VtrVote, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(VtrClass, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(VtrName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VtrMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VtrAge, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(VtrGen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(VtrPw))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(394, 394, 394)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(VtrSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(VtrClassSrc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(VtrMajorSrc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(VtrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(VtrAge)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VtrGen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(VtrVote, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VtrPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VtrClass, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VtrMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddBtn)
                            .addComponent(EditBtn)
                            .addComponent(DeleteBtn)
                            .addComponent(DeleteBtnAll))
                        .addGap(18, 18, 18)
                        .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VtrSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(VtrClassSrc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VtrMajorSrc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void AddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBtnMouseClicked
        // TODO add your handling code here:
        if(VtrName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Name");
        } else if(VtrAge.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Age");
        } else if(VtrPw.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Password");
        } else if(VtrGen.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Please Enter Gender");
        } else if(VtrVote.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Please Enter Vote");
        } else if(VtrClass.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Please Enter Class");
        } else if(VtrMajor.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Please Enter Major");
        } else {
            try {
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/evotedb", "root", "");
                PreparedStatement Add = Con.prepareStatement("INSERT INTO tb_voters VALUES(?,?,?,?,?,?,?,?)");
                VotersCount();
                Add.setInt(1, VId);
                Add.setString(2, VtrName.getText());
                Add.setInt(3, Integer.valueOf(VtrAge.getText()));
                Add.setString(4, VtrPw.getText());
                Add.setString(5, VtrGen.getSelectedItem().toString());
                Add.setString(6, VtrClass.getSelectedItem().toString());
                Add.setString(7, VtrMajor.getSelectedItem().toString());
                Add.setString(8, VtrVote.getSelectedItem().toString());
                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Voter Registered");
                Con.close();
                VtrName.setText("");
                VtrAge.setText("");
                VtrPw.setText("");
                VtrGen.setSelectedIndex(0);
                VtrClass.setSelectedIndex(0);
                VtrMajor.setSelectedIndex(0);
                VtrVote.setSelectedIndex(0);
                DisplayVoters();
                WidthColumn();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Voter Unregistered");
            }
        }
    }//GEN-LAST:event_AddBtnMouseClicked

    private void DeleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBtnMouseClicked
        // TODO add your handling code here:
        if(VId == 0) {
            JOptionPane.showMessageDialog(this, "Select The Voter To Be Deleted");
        } else {
            int ok = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the data", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);
            if(ok == 0) {
                try {
                    Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/evotedb", "root", "");
                    String Query = "DELETE FROM tb_voters WHERE No = " + VId;
                    Statement Del = Con.createStatement();
                    Del.executeUpdate(Query);
                    JOptionPane.showMessageDialog(this, "Voter Deleted Successfully");
                    VtrName.setText("");
                    VtrAge.setText("");
                    VtrPw.setText("");
                    VtrGen.setSelectedIndex(0);
                    VtrClass.setSelectedIndex(0);
                    VtrMajor.setSelectedIndex(0);
                    VtrVote.setSelectedIndex(0);
                    DisplayVoters();
                    WidthColumn();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Voter Deleted Failed");
                }   
            }
        }
    }//GEN-LAST:event_DeleteBtnMouseClicked

    private void VtrTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VtrTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)VtrTable.getModel();
        int MyIndex = VtrTable.getSelectedRow();
        VId = Integer.valueOf(model.getValueAt(MyIndex, 0).toString());
        VtrName.setText(model.getValueAt(MyIndex, 1).toString());
        VtrAge.setText(model.getValueAt(MyIndex, 2).toString());
        VtrPw.setText(model.getValueAt(MyIndex, 3).toString());
        VtrGen.setSelectedItem(model.getValueAt(MyIndex, 4).toString());
        VtrClass.setSelectedItem(model.getValueAt(MyIndex, 5).toString());
        VtrMajor.setSelectedItem(model.getValueAt(MyIndex, 6).toString());
        VtrVote.setSelectedItem(model.getValueAt(MyIndex, 7).toString());
    }//GEN-LAST:event_VtrTableMouseClicked

    private void DeleteBtnAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBtnAllMouseClicked
        // TODO add your handling code here:
        if(VId == 0) {
            JOptionPane.showMessageDialog(this, "Select The Voter To Be Deleted");
        } else {
            int ok = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete all the data", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);
            if(ok == 0) {
                try {
                    Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/evotedb", "root", "");
                    String Query = "DELETE FROM tb_voters";
                    Statement Del = Con.createStatement();
                    Del.executeUpdate(Query);
                    JOptionPane.showMessageDialog(this, "Voters Deleted Successfully");
                    VtrName.setText("");
                    VtrAge.setText("");
                    VtrPw.setText("");
                    VtrGen.setSelectedIndex(0);
                    VtrClass.setSelectedIndex(0);
                    VtrMajor.setSelectedIndex(0);
                    VtrVote.setSelectedIndex(0);
                    DisplayVoters();
                    WidthColumn();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Voters Deleted Failed");
                }   
            }
        }
    }//GEN-LAST:event_DeleteBtnAllMouseClicked

    private void EditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseClicked
        // TODO add your handling code here:
        if(VId == 0) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            try {
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/evotedb", "root", "");
                String Query = "UPDATE tb_voters SET Name = ?, Age = ?, Password = ?, Gender = ?, Class = ?, Major = ?, Vote = ? WHERE No = " + VId;
                PreparedStatement Update = Con.prepareStatement(Query);
                Update.setString(1, VtrName.getText());
                Update.setInt(2, Integer.valueOf(VtrAge.getText()));
                Update.setString(3, VtrPw.getText());
                Update.setString(4, VtrGen.getSelectedItem().toString());
                Update.setString(5, VtrClass.getSelectedItem().toString());
                Update.setString(6, VtrMajor.getSelectedItem().toString());
                Update.setString(7, VtrVote.getSelectedItem().toString());
                Update.executeUpdate();
                JOptionPane.showMessageDialog(this, "Voter Update Successfully");
                VtrName.setText("");
                VtrAge.setText("");
                VtrPw.setText("");
                VtrGen.setSelectedIndex(0);
                VtrClass.setSelectedIndex(0);
                VtrMajor.setSelectedIndex(0);
                VtrVote.setSelectedIndex(0);
                DisplayVoters();  
                WidthColumn();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Voter Update Failed");
            }
        }
    }//GEN-LAST:event_EditBtnMouseClicked

    private void FindDataName(String Key) {
        DefaultTableModel TableFind = new DefaultTableModel();
        TableFind.addColumn("No");
        TableFind.addColumn("Name");
        TableFind.addColumn("Age");
        TableFind.addColumn("Password");
        TableFind.addColumn("Gender");
        TableFind.addColumn("Class");
        TableFind.addColumn("Major");
        TableFind.addColumn("Vote");
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/evotedb", "root", "");
            Statement st = Con.createStatement();
            ResultSet Find = st.executeQuery("SELECT * FROM tb_voters WHERE Name LIKE '%" + Key + "%'");
            while (Find.next()) {
                TableFind.addRow(new Object[] {
                    Find.getString(1),
                    Find.getString(2),
                    Find.getString(3),
                    Find.getString(4),
                    Find.getString(5),
                    Find.getString(6),
                    Find.getString(7),
                    Find.getString(8),
                });
            }
            VtrTable.setModel(TableFind);
            WidthColumn();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    
    private void VtrSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VtrSearchKeyReleased
        // TODO add your handling code here:
        String Key = VtrSearch.getText();
        
        if(Key != "") {
            FindDataName(Key);
        } else {
            DisplayVoters();
            WidthColumn();
        }
    }//GEN-LAST:event_VtrSearchKeyReleased
    
    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnMouseClicked

    private void FindDataClass(String Key) {
        DefaultTableModel TableFind = new DefaultTableModel();
        TableFind.addColumn("No");
        TableFind.addColumn("Name");
        TableFind.addColumn("Age");
        TableFind.addColumn("Password");
        TableFind.addColumn("Gender");
        TableFind.addColumn("Class");
        TableFind.addColumn("Major");
        TableFind.addColumn("Vote");
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/evotedb", "root", "");
            Statement st = Con.createStatement();
            ResultSet Find = st.executeQuery("SELECT * FROM tb_voters WHERE Class = '" + Key + "'");
            while (Find.next()) {
                TableFind.addRow(new Object[] {
                    Find.getString(1),
                    Find.getString(2),
                    Find.getString(3),
                    Find.getString(4),
                    Find.getString(5),
                    Find.getString(6),
                    Find.getString(7),
                    Find.getString(8),
                });
            }
            VtrTable.setModel(TableFind);
            WidthColumn();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    
    private void VtrClassSrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VtrClassSrcActionPerformed
        // TODO add your handling code here:
        if(VtrClassSrc.getSelectedItem()== "X") {
            FindDataClass("X");
        } else if(VtrClassSrc.getSelectedItem() == "XI") {
            FindDataClass("XI");
        } else if(VtrClassSrc.getSelectedItem() == "XII") {
            FindDataClass("XII");
        } else {
            DisplayVoters();
            WidthColumn();
        }
    }//GEN-LAST:event_VtrClassSrcActionPerformed

    private void FindDataMajor(String Key) {
        DefaultTableModel TableFind = new DefaultTableModel();
        TableFind.addColumn("No");
        TableFind.addColumn("Name");
        TableFind.addColumn("Age");
        TableFind.addColumn("Password");
        TableFind.addColumn("Gender");
        TableFind.addColumn("Class");
        TableFind.addColumn("Major");
        TableFind.addColumn("Vote");
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/evotedb", "root", "");
            Statement st = Con.createStatement();
            ResultSet Find = st.executeQuery("SELECT * FROM tb_voters WHERE Major = '" + Key + "'");
            while (Find.next()) {
                TableFind.addRow(new Object[] {
                    Find.getString(1),
                    Find.getString(2),
                    Find.getString(3),
                    Find.getString(4),
                    Find.getString(5),
                    Find.getString(6),
                    Find.getString(7),
                    Find.getString(8),
                });
            }
            VtrTable.setModel(TableFind);
            WidthColumn();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    
    private void VtrMajorSrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VtrMajorSrcActionPerformed
        // TODO add your handling code here:
        if(VtrMajorSrc.getSelectedItem()== "TKJ") {
            FindDataMajor("TKJ");
        } else if(VtrMajorSrc.getSelectedItem() == "MM") {
            FindDataMajor("MM");
        } else if(VtrMajorSrc.getSelectedItem() == "Farmasi") {
            FindDataMajor("Farmasi");
        } else if(VtrMajorSrc.getSelectedItem() == "OTKP") {
            FindDataMajor("OTKP");
        } else if(VtrMajorSrc.getSelectedItem() == "TKRO") {
            FindDataMajor("TKRO");
        } else {
            DisplayVoters();
            WidthColumn();
        }
    }//GEN-LAST:event_VtrMajorSrcActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Voters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Voters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Voters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Voters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Voters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton DeleteBtnAll;
    private javax.swing.JButton EditBtn;
    private javax.swing.JTextField VtrAge;
    private javax.swing.JComboBox<String> VtrClass;
    private javax.swing.JComboBox<String> VtrClassSrc;
    private javax.swing.JComboBox<String> VtrGen;
    private javax.swing.JComboBox<String> VtrMajor;
    private javax.swing.JComboBox<String> VtrMajorSrc;
    private javax.swing.JTextField VtrName;
    private javax.swing.JTextField VtrPw;
    private javax.swing.JTextField VtrSearch;
    private javax.swing.JTable VtrTable;
    private javax.swing.JComboBox<String> VtrVote;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
